server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-odv3v-kr.vpc-pub-cdb.ntruss.com/trivi
    username: trivi
    password: trivi407!
  servlet:
    multipart:
      resolve-lazily: true

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

cloud:
  aws:
    credentials:
      instanceProfile: true
      access-key: test
      secret-key: test
    s3:
      bucket-name: trivi407
    region:
      static: ap-northeast-2
    stack:
      auto: false
